#! /bin/bash

themechangerconfig=$XDG_CONFIG_HOME/theme_changer/config
kittythemedir=$XDG_CONFIG_HOME/kitty/ 
kittyconf=$kittythemedir/kitty.conf
vimrcdir=$XDG_CONFIG_HOME/nvim/init.vim
wallpaperdir=$XDG_PICTURES_DIR/Wallpapers/

# Parse the config file to pipe into feh (not really pipe but whatever)
parse_config() {
    sed -n -r "
        /$1:/,/^$/ {
            s:^\s{4}:$wallpaperdir:p
        }
        " $themechangerconfig
}

# Changes the wallpaper to a light or dark colorscheme to a random wallpaper
# according to the config file. Also updates the betterlockscreen image.
change_wallpaper() {
    wallpaper="$(parse_config $1 | shuf -n1)"
    case $1 in
        light) feh --bg-scale "$wallpaper" ;;
        dark) feh --bg-scale "$wallpaper" ;;
    esac
    betterlockscreen -u "$wallpaper"
}

# Changes the kitty colors on the active kitty terminals and modifies the config
# to preserve the colors even if all the terminals are closed.
change_terminal_theme() {
    kitty @ --to unix:/tmp/kitty set-colors --all --configured $kittythemedir/$1
    sed -i '
        /^#: REPLACE SECTION$/,/^#: END REPLACE SECTION$/ {
            R '"$kittythemedir/$1"'
            D
        }
        ' $kittyconf
}

theme_changer () {
    change_terminal_theme $1
}

if kitty @ --to unix:/tmp/kitty get-colors | grep -q -E "background +#00191f"; then
    theme_changer light 
else
    theme_changer dark
fi
